#! /bin/bash

# add example_user for test
sudo useradd -m example_user
stdlib::info "Checking whether to add any users to sudoers ..."
stdlib::setup_sudoers

URL=${URL:-"http://ifconfig.co/json"}
stdlib::info "Fetching ${URL}"
stdlib::cmd curl --silent "${URL}"
echo
